#!/bin/bash

export WEB_APP_HTTP_URL=[HTTP/S URL OF YOUR APP GOES HERE]
export APP_SESSION_SECRET=fldjajskl_CUSTOMIZE_THIS_fdhjasljkhfa
export AUTH0_AUTH_DOMAIN=[YOUR AUTH0 DOMAIN GOES HERE]
export AUTH0_AUDIENCE=[YOUR AUTH0 API AUDIENCE]
export AUTH0_CLIENT_ID=[YOUR AUTH0 CLIENT ID]
export AUTH0_CLIENT_SECRET=[YOUR AUTH0 CLIENT SECRET]